import { Marker, Popup } from "react-leaflet";
import L from "leaflet";
import useLocalization from "../../hooks/useLocalization";

const estimatedIcon = new L.DivIcon({
  html: `
    <div style="
      width:18px;
      height:18px;
      background:#f59e0b;
      border:3px solid white;
      border-radius:50%;
      box-shadow:0 0 20px rgba(245,158,11,.8);
    "></div>
  `,
  className: "",
  iconSize: [18, 18],
});

export default function EstimatedLocationMarker() {
  const { data, loading } = useLocalization();

  if (loading || !data) return null;

  return (
    <Marker
      position={[
        data.heatmapCenter.lat,
        data.heatmapCenter.lng,
      ]}
      icon={estimatedIcon}
    >
      <Popup>
        <div className="min-w-[220px]">
          <h3 className="font-bold mb-2">
            📍 Estimated Location
          </h3>

          <p>
            Confidence: {data.confidence}%
          </p>

          <p>
            Radius: {data.radius} m
          </p>

          <p>
            Direction: {data.direction}
          </p>

          <p>
            Nearby Towers: {data.nearbyTowers}
          </p>

          <p className="mt-2 text-xs text-gray-500">
            Highest probability estimate generated by the localization engine.
          </p>
        </div>
      </Popup>
    </Marker>
  );
}